source 'https://rubygems.org'

gem 'allure-cucumber'
gem 'allure-rspec'
gem 'appium_lib'
gem 'cucumber'
gem 'faker'
gem 'fig_newton'
gem 'page-object'
gem 'rake'
gem 'require_all'
gem 'rest-client'
gem 'rspec'
gem 'rspec-expectations'
gem 'sauce_whisk'
gem 'spec'
gem 'test-unit'
